language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t hileuski/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true hileuski/docker-react npm run test